### ISSUE TITLE
Matrix Package

### ISSUE THREAD

**Issue by andyleejordan** [westrope/CS324-Graphics-Assignment4#2]
I don't know about you, but as long as you're not barred from this, if you're going to be doing any sort of matrix math, what about [JAMA](http://math.nist.gov/javanumerics/jama/), or any other matrix package?

I'm trolling, but don't go reinventing wheels. Or matrices.

**Comment by westrope** [comment]
Yeah I figured that Java had a matrix package, but I'm not sure if we can use it. And it's super simple to write a basic matrix class. All we need it for is doing matrix multiplication which is just a few lines of code. Now that I think about it I don't think we can use any outside matrix classes, at least that's what a few people have said. But it only took like 15 minutes to code up.
